# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"
tasks:
  default:
    cmds:
      - task: build

  build:
    vars:
      MODE: '{{.MODE | default "debug"}}'
    cmds:
      - cargo build {{if eq .MODE "release"}}--release{{end}}

  link:
    deps: [build]
    dir: bin
    cmds:
      - ln -sf ../target/debug/mdlr .

  install:
    dir: "{{.ROOT_DIR}}"
    cmds:
      - cargo install --path . --root $HOME/.local
