# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"
tasks:
  default:
    cmds:
      - task: build

  run:
    deps: [build]
    cmd: mdlr {{.CLI_ARGS}}

  build:
    vars:
      MODE: '{{.MODE | default "debug"}}'
      QUIET: '{{.QUIET | default "false"}}'
    cmds:
      - cargo build {{if eq .MODE "release"}}--release{{end}} {{if eq .QUIET "true"}}2>/dev/null{{end}}

  build-go:
    dir: tools/mdlr-extract-go
    cmds:
      - go build -o ../../bin/mdlr-extract-go .

  link:
    vars:
      QUIET: '{{.QUIET | default "false"}}'
    deps:
      - task: build
        vars:
          QUIET: "{{.QUIET}}"
      - task: build-go
    dir: bin
    cmds:
      - ln -sf ../target/debug/mdlr .

  check:
    deps:
      - task: link
        vars: { QUIET: "true" }
    cmds:
      - mdlr check

  install:
    dir: "{{.ROOT_DIR}}"
    cmds:
      - cargo install --path crates/mdlr --root $HOME/.local
      - cd tools/mdlr-extract-go && go build -o $HOME/.local/bin/mdlr-extract-go .
